name: lifeec_mobile
description: "Professional Elderly Care System Mobile Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  google_fonts: ^6.2.1
  fl_chart: ^0.63.0
  timeago: ^3.2.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Health.svg